sudo: required
services:
  - docker


before_install:
  - docker build -t mahadevaprasadap/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mahadevaprasadap/docker-react npm run test

deploy:
  provider: elasticbeanstalk  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "ap-south-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-174718991791" 
