sudo: required
services:
  - docker


before_install:
  - docker build -t mahadevaprasadap/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mahadevaprasadap/docker-react npm run test